version: '3.9'

services:
  backend:
    build: ./backend
    container_name: elimu_backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]

  frontend:
    build: ./frontend
    container_name: elimu_frontend
    ports:
      - "5173:5173"
    command: [ "npm", "run", "dev" ]
    volumes:
      - ./frontend:/app
